Repository scalefocus/virusafe-ios, pull requests merged in 2020-05, with the labels that each got.

#14 Add functionality to opt-out/in from processing personal data.
  COVID-19/AppDelegate.swift
  COVID-19/Models/Flow Manger/AppFlowManager.swift
  COVID-19/Repositories/PersonalInformationRepository.swift
  COVID-19/Repositories/TermsAndConditionsRepository.swift
  COVID-19/Scenes/EGNScene/PersonalInformation.storyboard
  COVID-19/Scenes/EGNScene/PersonalInformationViewController.swift
  COVID-19/Scenes/EGNScene/PersonalInformationViewModel.swift
  COVID-19/Scenes/HomeScene/HomeViewController.swift
  COVID-19/Scenes/RegisterScene/RegistrationViewController.swift
  COVID-19/Scenes/RegisterScene/RegistrationViewModel.swift
  COVID-19/Scenes/Registration.storyboard
  COVID-19/Scenes/RegistrationConfirmationScene/RegistrationConfirmationViewController.swift
  ModuleFrameworks/NetworkKit/NetworkKit/Requests/DeletePersonalInformationRequest.swift
Labels: enhancement

#10 Setup CI file
  .fonts/fonts.gpg
  .github/pull_request_template.md
  .github/scripts/pre-build-steps.sh
  .github/scripts/validate-branch-name.sh
  .github/scripts/validate-code-style.sh
  .github/workflows/branch_name.yml
  .github/workflows/ci-develop.yml
  .github/workflows/ci-release.yml
  .github/workflows/lint.yml
  .gitignore
  .swiftlint.yml
  CONTRIBUTING.md
  COVID-19.xcodeproj/project.pbxproj
  COVID-19.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  COVID-19.xcodeproj/xcshareddata/xcschemes/NorthMacedonia.xcscheme
  COVID-19.xcodeproj/xcshareddata/xcschemes/Production.xcscheme
  COVID-19.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  COVID-19/Extensions/UIViewExtension.swift
  COVID-19/Info.plist
  COVID-19/Repositories/LocationRepository.swift
  COVID-19/Scenes/EGNScene/PersonalInformationViewModel.swift
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  README.md
  fastlane/.gitignore
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/README.md
Labels: enhancement, help wanted

#21 Add Permissions Scope document
  Permission-Scope.md
Labels: documentation
